### ISSUE TITLE
System setting gets not rendered properly

### ISSUE THREAD

**Issue by earnur91** [sepiariver/cssSweet#1]
Hi there! I've made a custom system setting called [[++theme_path]] which represents the path to my theme directory. [[++theme_path]] consists of [[++assets_url]]themes/[[++theme]]/. So to keep the overview of my files, I wanted to set the csss.custom_css_path to [[++theme_path]]css/. The problem is, the path isn't rendered properly so the file was put in /connectors/system/[[++theme_path]]css/.

Regards and thank you for the work so far :+1:

**Comment by DESIGNfromWITHIN** [comment]
This does not work for me see #9

**Comment by sepiariver** [comment]
In V2+ the query for system settings is removed entirely and only plugin properties are used.
