### ISSUE TITLE
Update scssphp

### ISSUE THREAD

**Issue by Boddlnagg** [sepiariver/cssSweet#14]
Since the last release of cssSweet, many bugs have been fixed in scssphp (and I think the compilation performance has improved as well).

**Comment by sepiariver** [comment]
Thanks for letting me know, I'll try to get it inthe next version very soon!

**Comment by sepiariver** [comment]
Done https://github.com/sepiariver/cssSweet/commit/d960c5c060d9d253b562661d4fd1fe71d45a7060
