### ISSUE TITLE
Error when clearing cache

### ISSUE THREAD

**Issue by Boddlnagg** [sepiariver/cssSweet#16]
When I clear the cache via the manager, the console that pops up contains the following message:
```
saveCustomCss plugin is running in mode: custom
$csssCustomCssPath is: /www/htdocs/w0131692/dev/assets/components/csssweet/ on line: 68
Failed to load ClientConfig class. ClientConfig settings not included.
Processing chunk: csss.custom_css.scss
$modx->getChunk() failed on line: 113 for chunk: csss.custom_css.scss
saveCustomJs plugin is running in mode: custom
No chunks were set in the saveCustomJs plugin property: custom_js_chunks. No action performed.
```

The problematic line is the fifth one (and it's printed in red): I don't use the chunk `csss.custom_css.scss` (and it doesn't exist), and I have the plugin setting `custom_scss_chunks` overwritten in a property set. So cssSweet should not try to do anything with that chunk.

**Comment by sepiariver** [comment]
Can you ensure that the cssSweet Plugin events have been configured to fire with the custom property set and not the default one? If you don't intend to run it in the clear cache event at all, it would be better to disable that event, but if you do, you must specify the property set.

Let me know if that helps.

**Comment by Boddlnagg** [comment]
Oh, right. The OnSiteRefresh event was still configured to use the default property set. It works now, thanks for the hint! Maybe the documentation could be improved concerning the property sets?

**Comment by sepiariver** [comment]
Will create an issue for documentation :) Thanks
