### ISSUE TITLE
System Settings Missing

### ISSUE THREAD

**Issue by natedin** [sepiariver/cssSweet#20]
Hi,

I'm running cssSweet 3.0.0-beta3 and modx 2.5.1, everything seems to install fine but I have no System Settings showing up for cssSweet (unless this has changed?).

I've changed folder permissions to 777 and reinstalled with no luck, nothing in modx error log either

Edit: just tried the csssweet-4.0.0-dev1.transport.zip from github and still no joy

Thanks

**Comment by atorockio** [comment]
Hello,

According to https://rtfm.modx.com/extras/revo/csssweet/

> As of version 2, the cssSweet system settings have been deprecated in favour of plugin properties.

Everything is now set up in the plugin properties. If you have a new install of cssSweet you will not see the old system settings.

Ann

**Comment by sepiariver** [comment]
Thank you so much @atorockio for answering @natedin 's question. You are correct that the System Settings were deprecated.

Sorry for the slow response on my part. I will try to do better in future.
