### ISSUE TITLE
Refresh css files when clientConfig settings are updated?

### ISSUE THREAD

**Issue by atorockio** [sepiariver/cssSweet#21]
Hi, I have just started using cssSweet and loving it. Is it possible to make the css files update whenever clientConfig setting are saved?

Any tips on how to write something like that or (of course!) a solution would be much appreciated. There is a [feature request for clientConfig](https://github.com/Mark-H/ClientConfig/issues/83) to have a system event triggered when clientConfig settings are updated which would make it a lot easier to get theses two great packages working together seamlessly. Maybe there is another way?

Thanks for any help!

**Comment by sepiariver** [comment]
I'll look into this but I'm wary of hooking up the plugin to events like OnCacheUpdate because it can get triggered excessively.

The custom ClientConfig event would be ideal. I'll plus one the FR :)

**Comment by sepiariver** [comment]
@atorockio do you know if the modmore team released a version of ClientConfig that triggers a custom event?

**Comment by atorockio** [comment]
Hi, yes they added the system event ClientConfig_ConfigChange in version 1.4.0 :-)

**Comment by sepiariver** [comment]
Resolved: in 640126527f6643c386eedc17b9cefa602dd74105
