### ISSUE TITLE
JS Plugin broken

### ISSUE THREAD

**Issue by Camo30** [sepiariver/cssSweet#25]
When clearing the site cache with modx release 2.6 I get some errors:

> Processing chunk: jquery-1.12.4.min.js
Could not find snippet with name "resolve","done",n.Callbacks("once memory"),"resolved"],["reject","fail",n.Callbacks("once memory"),"rejected"],["notify","progress",n.Callbacks("memory").
Could not find snippet with name \w\W]*\])$/,O=/([A-Z])/g;function P(a,b,c){if(void 0===c&&1===a.nodeType){var d="data-"+b.replace(O,"-$1").toLowerCase();if(c=a.getAttribute(d),"string"==typeof c){try{c="true"===c.

Up to modx release 2.5.8 it worked flawlessly with exactly the same files. Do you have an idea whats wrong with it? CSS is working fine

**Comment by sepiariver** [comment]
Hi @Camo30 

In 2.6+ MODX logs an error when a Snippet call is made where no such Snippet exists. In some cases, Javascript syntax causes a collision with MODX tag syntax, for example an array of arrays.
`[[1,2,3],["array","of","arrays"]]` 

Try including the **un**minified version of jQuery, in which double-brackets are far less likely to be used. The JS plugin will minify it for you in the output.

Let me know how that goes...

**Comment by Camo30** [comment]
Hi sepiariver, you are right, using the unminified versions solves the problem. Thank you very much for your help!
