### ISSUE TITLE
Always problems

### ISSUE THREAD

**Issue by funkyduke** [sepiariver/cssSweet#26]
Always when I upgrade from 3 to 4 there are problems and the css-file is not wel saved. Empty cache keeps hanging on "Applying scssphp formatter class: Leafo\ScssPhp\Formatter\Crunched". So I'm left with an empty css-file.

Why does it goes wrong? In the documentation said there's no problem upgrading form 2 or 3 to 4.

**Comment by tassu** [comment]
I got csssweet 4.2.0-rc3 in use in modx 2.6.5. in one site. Default settings saves ok. But if  i make custom properties set and change chunks, name or path it hangs. (Last line: Applying scssphp formatter class: Leafo\ScssPhp\Formatter\Compressed).

Removed, reinstalled, deleted cache and so on, but it still hangs.  Reset settings default then it works. Then added custom settings, it stops working. No errors in error log.

All my css are static and they work alone fine.

I use this extra with same manners quite many sites where it works like charm. But one site is pain.

All sites running lamp servers in same provider. Tried different php versions (now 7.1) but no help.

I tried different combinations in settings and sometimes it works and writes css fine.

**Comment by tassu** [comment]
More on issue that I have. Reinstalled extra (completly removed first). Default saving ok. Added property set with default settings and set it to system settings, save ok. Changed name of css, save ok. Added chunks (static css files), save ok to components folder. Then cleared cache again and it hangs.

It seems when ever I put chunks to process it hangs. Tried php 7.1 and 5.6.

Here is console output:
saveCustomCss plugin is running in mode: custom
$csssCustomCssPath is: /home/xxxxx/public_html/assets/components/csssweet/custom/ on line: 93
Processing chunk: foundation.css
Processing chunk: app.css
Processing chunk: top-bar-modattu.css
Processing chunk: buttons.css
Processing chunk: normalize.css
Applying scssphp formatter class: Leafo\ScssPhp\Formatter\Compressed

No savings.

**Comment by tassu** [comment]
Did more debugging. Added all css to the default scss file (not static) revert to default that setting. Same output and no saving. Now even default settings don`t save and console hangs.

I have to give up and ask server admin if he finds out in logs what is going on.

**Comment by tassu** [comment]
SOLVED! Check also Strip comments to yes it start to work!

**Comment by tassu** [comment]
Note! Setting strip comments to yes too helped a bit, but still sometimes console hangs.

**Comment by tassu** [comment]
Solved hopefully! Problem was in custom properties. Copied from default and then turned on minification and leaved default "Expanded" in Format settings. Removed Expanded format and now it seems to work.

**Comment by sepiariver** [comment]
Hi @tassu sorry you had issues with this. If I understand correctly, it was the “Expanded” format you were having issues with?

Trying to determine if latest scss-php that was updated has some bugs with a specific formatter class...

**Comment by tassu** [comment]
I`m not sure what is causing issues. They seem very random. Now I haven`t any problems with extra for a long time. Also it could be that it process some of the  complex (like foundation 5 top-bar css) css chunks very slow on online servers.

**Comment by sepiariver** [comment]
Ok thanks for the feedback @tassu I'll close this for now, and update the scssphp library soon. Please let me know if you have any further issues. I've fixed my Github notifications so I'll see these as they come in :)
