### ISSUE TITLE
scss_import_paths is being ignored

### ISSUE THREAD

**Issue by travisbotello** [sepiariver/cssSweet#27]
First of all I tried to include the example `test.scss` file. Which results in:

`@import url("/ass3ts/components/csssweet/custom/test.scss");`

Which is wrong by default because the files is located here `/ass3ts/components/csssweet/scss`. So I tried to overwrite the `scss_import_paths` settings. I created my own property set, saved a custom path and changed the plugin properties to use my custom property set. Still the same issue in generated css file. Looks like it is not picking up the path:

`@import url("/ass3ts/components/csssweet/custom/test.scss");`

I am running MODx 2.6.5 with CSSSweet 4.2.0-rc3. As you can see I am using a custom `assets` path. Process tags in properties is checked. Don't know if this is related.

**Comment by travisbotello** [comment]
Hmm...only absolute paths seem to be working.

Not working: `[[++assets_path]]ass3ts/custom/path/to/scss/`

Working: `/home/sites/modx/ass3ts/custom/path/to/scss/`

Process tags in properties is activated. Is this expected?

**Comment by travisbotello** [comment]
My bad...mistaken `[[++assets_url]]` with `[[++assets_path]]`. So my actual issue for this is resolved, however default/empty `scss_import_paths` and `test.scss` are still configured wrong. Maybe someone is interested to fix this.

**Comment by LucyI** [comment]
I'm having issues with paths as well and realized the docs have the wrong MODX placeholder and path for the minified css file. The default location is:
`[[++assets_url]]components/csssweet/custom/custom_css.min.css`

But the docs show:
`[[++assets_path]]components/csssweet/custom_css.min.css`

Here's a screenshot where the docs can be updated:
![sepiariver github io-20220505-1249](https://user-images.githubusercontent.com/810839/167018271-7c416d1a-3513-4042-8d57-30bcd903507f.jpg)

**Comment by sepiariver** [comment]
When you reference the output CSS file in your templates or chunks to be rendered as a page, you absolutely want to use assets_url and NOT  assets_path as the latter will reveal your server root’s path. 

The browser will not be able to access the file using assets_path and for security reasons it is preferable to keep your server directory structure hidden

**Comment by sepiariver** [comment]
I guess I might ask, or should have asked before even responding lol

From which documentation did you capture that screenshot ?

**Comment by sepiariver** [comment]
Never mind I found it sorry fixing now :)
