### ISSUE TITLE
PHP warning: strpos(): Empty needle

### ISSUE THREAD

**Issue by crimsonpixel** [sepiariver/cssSweet#29]
Upgrade cssSweet to latest version but getting this error message in the logs refering to:

`components/csssweet/model/csssweet/csssweet.class.php : 407) PHP warning: strpos(): Empty needle`

What is this referring to?  

Also when I clear the cache I receive the following message relating to the plugin:

saveCustomCss plugin is running in mode:
PHP warning: strpos(): Empty needle
PHP warning: strpos(): Empty needle

**Comment by sepiariver** [comment]
Hi @crimsonpixel 

Thanks for pointing this out. The plugin tries to get the value of the `dev_mode` property from the Plugin's properties, and if it's empty it will default to "custom". It seems in your case it's empty. Can you please export your property set and email it to me at info at sepiariver.com or alternatively post it here?

It's the button at the bottom of the Properties tab when you edit the saveCustomCss Plugin:

![Screenshot 2019-10-07 17 27 19](https://user-images.githubusercontent.com/821671/66358477-e8308100-e927-11e9-8083-269a8f867b86.png)

**Comment by crimsonpixel** [comment]
I've emailed propertyset to you today as requested.  Let me know if you received it :)

**Comment by sepiariver** [comment]
Was this upgraded from a very early version of csssweet?

**Comment by crimsonpixel** [comment]
I've got this error on a few sites where I've upgraded the extra, the only one where I haven't purge old packages shows the previous versions as 4.2.0 and 3.0.0.

**Comment by sepiariver** [comment]
Sorry for the long delay on this @crimsonpixel 
I've added some defence for this issue in 3c4c17a12fbc995b8fb61fccbd938dab11db7574
