### ISSUE TITLE
How can I get FRED to add a Property set for cssSweet and set custom system events for the cssSweet plugin?

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [sepiariver/cssSweet#30]
Have the perfect color editing now for my theme using clientConfig and cssSweet, just need Fred to somehow set these custom system events and The Property set for cssSweet.

**Comment by sepiariver** [comment]
Hi @DESIGNfromWITHIN i think it needs to be some kind of resolver in the FRED package but I don’t know anything about FRED packaging. Would you happen to know if there’s documentation on building packages with FRED?
