### ISSUE TITLE
System settings empty in MODX 3.0.1 and 2.8.4

### ISSUE THREAD

**Issue by valokammi** [sepiariver/cssSweet#32]
Affects Dev and production sites. 
Dev enviroment is Laragon, win 10, php 7.4.29. Issue is both 3.0.1 and 2.8.4. CssSweet version 5.2.0-beta1.
There is no system settings viewable in system settings for CssSweet at all.
When clearing cache it seems to work and new css files are created or updated.
Deleted cache files and reinstalled (2.8.4, 3.0.1 fresh install) but no help.
No errors in error log.

**Comment by valokammi** [comment]
In 2.8.4 old install (tried reinstall with no help) and 3.0.1 fresh one.
![Untitled-1](https://user-images.githubusercontent.com/1112163/166715099-0b806bd7-94b3-45e1-8d72-dfe3248bbcf4.png)
![Untitled-2](https://user-images.githubusercontent.com/1112163/166715102-545c7ca0-2e1d-49e4-81c5-5278310f42b3.png)
.

**Comment by sepiariver** [comment]
Ok great thanks 

sorry last question if you please 

I’m trying to determine if the settings were installed but do not display. There were some changes to files types if I recall correctly 

If you can check the system settings table in the database for existence of csssweet settings, that would confirm. Another way to check may be errors in the browser console on the system settings page but that is less reliable

**Comment by valokammi** [comment]
There is nothing with namespace csssweet in system settings table!

**Comment by valokammi** [comment]
search results for system settings table csssweet namespace :
MySQL returned an empty result set (i.e. zero rows). (Query took 0.0005 seconds.)

**Comment by valokammi** [comment]
Rolled devserver back to 2.8.3. No csssweet system setting there too!

**Comment by valokammi** [comment]
Did some investigation with old (2.6.4 was oldest) databases and there were nothing in system settings there any of them. All settings that were done was stored in property_set table.

**Comment by valokammi** [comment]
I looked some old (oldest 2.7.x) databases and none have csssweet system_settings. Other entries found but no system settings.

**Comment by sepiariver** [comment]
Ok I’m so sorry

looking at the ticket title I “ass-umed” there should be system settings. It’s has been 2.5 years since I looked at the build config so I forgot: there are no system settings for this package

The settings are all managed in the plug-in 

did you encounter an error message somewhere that said system settings were missing?

my apologies again, my bad

**Comment by valokammi** [comment]
Actually this is my bad (RTFM!!!!).

To me it is been so long time to configure csssweet that I`ve forgot it. After installing it to Modx 3 start to wonder where to cofigure it and as allways started to look systems settings.

Theres no errors anywhere works like charm so far in Modx 3.

**Comment by sepiariver** [comment]
Excellent!! Thank you so much :)
