### ISSUE TITLE
Displaying TVs with Media Sources

### ISSUE THREAD

**Issue by pawelmil** [sepiariver/cssSweet#5]
TV media source path is not displaying after saving to file, when
 I try to display tv value of specific document, eg.:
normally [[#.11.variable-file]]  gives output: mediasource/path/file.txt <br/>
but when I put this code in csssweet chunk it displays: file.txt

**Comment by sepiariver** [comment]
@pawelmil does this work with the newest version of cssSweet? (Note that version has an unrelated bug with the file saving path on new installs, which has been fixed in a hot fix and will be packaged in 1.2.1 coming soon)

**Comment by pawelmil** [comment]
Hi, I don' use cssSweet now - I wrote raw snippet to save document (modresource with css type) to file and I avoid using snippets or media sources in css document as you suggested. I use resource instead of chunk becouse I see CSS markup with ACE editor. I'll install cssSweet and test it when I'll find some time. Thanks for great work!

**Comment by sepiariver** [comment]
Ok sounds like you have a good solution there, @pawelmil 

FYI, Susan Ottwell has a version of cssSweet that she uses with multiple Resources in a separate context. You may find it helpful, and in fact it may get merged in with this repo on next version.

Thanks for using MODX!

**Comment by pawelmil** [comment]
Thanks!

W dniu 2015-03-30 o 18:47, Sepia River pisze:
>
> Ok sounds like you have a good solution there, @pawelmil 
> <https://github.com/pawelmil>
>
> FYI, Susan Ottwell has a version of cssSweet that she uses with 
> multiple Resources in a separate context. You may find it helpful, and 
> in fact it may get merged in with this repo on next version.
>
> Thanks for using MODX!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sepiariver/cssSweet/issues/5#issuecomment-87746440>.
>

-- 

Z poważaniem,
Paweł Milewski

<http://www.pvi.pl/>

PVI.pl Magdalena Milewska
ul. Wspólna 5, 18-200 Wysokie Mazowieckie
NIP 722 143 94 42
e-mail: biuro@pvi.pl
tel. 694 453 884
www.pvi.pl <http://www.pvi.pl/>
