### ISSUE TITLE
Allow for 'darken' with colors

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [sepiariver/cssSweet#8]
It would be great if it would be possible to also darken colors (like lighten now).

**Comment by sepiariver** [comment]
@DESIGNfromWITHIN did you ever get this one working for you?

**Comment by DESIGNfromWITHIN** [comment]
Yes, this works fine.
Op 29 mrt. 2015 19:19 schreef "Sepia River" <notifications@github.com>:
